### ISSUE TITLE
parse fails on April

### ISSUE THREAD

**Issue by nidate** [pvorb/node-isodate#3]
on isodate@0.1.2

> var isodate = require('isodate');
> isodate('2011-03-01T00:00:00Z');
> Tue Mar 01 2011 09:00:00 GMT+0900 (JST)
> isodate('2011-04-01T00:00:00Z');
> Sun May 01 2011 09:00:00 GMT+0900 (JST)
> isodate('2011-05-01T00:00:00Z');
> Sun May 01 2011 09:00:00 GMT+0900 (JST)

**Comment by pvorb** [comment]
Wow, this is weird. But I fixed it. Thank you for the hint.

**Comment by pvorb** [comment]
I'm sorry. There's a new bug. Please wait for v0.1.4.

**Comment by pvorb** [comment]
Should work as expected now.
